### ISSUE TITLE
configuration of Activiti within tenant environments

### ISSUE THREAD

**Issue by diaowenyang** [hendisantika/SpringBoot-Security-JWT-Rest-API-Dynamic-Multi-Tenancy-MySQL-PostgreSQL#3]
Dear hendisantika：

    I hope this email finds you well. I am writing to express my gratitude for your significant contributions to the open-source community. Your project, "SpringBoot-Security-JWT-Rest-API-Dynamic-Multi-Tenancy-MySQL-PostgreSQL," has been immensely helpful to me.

    However, I have encountered a challenge regarding the configuration of Activiti within tenant environments. I would greatly appreciate your guidance on how to set up Activiti in such a way that different tenants can utilize it within their respective schemas.

    I understand that enabling this capability requires some additional configuration steps and potentially modifications to the existing setup. If you could provide me with some insights or point me in the right direction, I would be extremely grateful.

    Once again, thank you for your remarkable work and the valuable knowledge you have shared with the community. I look forward to hearing from you and learning more about configuring Activiti within tenant environments.

    Thank you for your time and consideration.

    Best regards,

    Diaowenyang

**Comment by hendisantika** [comment]
OK. Thanks for that.
